# Generated by Django 6.0.3 on 2026-03-20 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_campus_school_campus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('nightly', 'Nightly Automated'), ('manual', 'Manual')], max_length=10)),
                ('filename', models.CharField(max_length=500)),
                ('filepath', models.CharField(max_length=1000)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_size_kb', models.PositiveIntegerField(default=0)),
                ('date_range_from', models.DateField(blank=True, null=True)),
                ('date_range_to', models.DateField(blank=True, null=True)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='schools.campus')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generated_exports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
