# Generated by Django 6.0.3 on 2026-05-30 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MISDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('accumulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mis_data_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
