# Generated by Django 6.0.3 on 2026-05-30 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0002_misdatarequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MISReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_content', models.TextField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('sent_to_admin', models.BooleanField(default=False)),
                ('sent_to_admin_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_accumulator', models.BooleanField(default=False)),
                ('sent_to_accumulator_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mis_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mis_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
