# Generated by Django 6.0.3 on 2026-05-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0003_misreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='misreport',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
