# Generated by Django 6.0.3 on 2026-05-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0004_misreport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='misreport',
            name='sent_to_chronicle_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='misreport',
            name='sent_to_chronicle_master_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='misreport',
            name='sent_to_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='misreport',
            name='sent_to_super_admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
