# Generated by Django 6.0.3 on 2026-05-31 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0005_misreport_sent_to_chronicle_master_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misreport',
            old_name='coordinator',
            new_name='created_by',
        ),
    ]
