# Generated by Django 6.0.3 on 2026-08-10 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0006_rename_coordinator_misreport_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicleDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronicle_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chronicle_data_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='misdatarequest',
            name='chronicle_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_data_requests', to='export.chronicledatarequest'),
        ),
    ]
