# Generated by Django 6.0.3 on 2026-04-25 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(choices=[('exams_conducted', 'Exams Conducted'), ('school_activities', 'School Activities'), ('student_activities', 'Student Activities'), ('faculty_fdp_workshop_gl', 'Faculty FDP / Workshop / GL'), ('faculty_publications', 'Faculty Publications'), ('patents', 'Patents'), ('certifications', 'Certifications'), ('placement_activities', 'Placement Activities'), ('courses', 'Courses'), ('academic_years', 'Academic Years'), ('semesters', 'Semesters'), ('subjects', 'Subjects'), ('class_groups', 'Class Groups'), ('exam_groups', 'Exam Groups'), ('clubs', 'Clubs')], max_length=100)),
                ('record_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('old_data', models.JSONField()),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='audit_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_requests', to='schools.school')),
            ],
            options={
                'db_table': 'audit_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='audit_reque_status_a9cebe_idx'), models.Index(fields=['table_name', 'record_id'], name='audit_reque_table_n_b278b8_idx'), models.Index(fields=['requested_by'], name='audit_reque_request_0625b0_idx'), models.Index(fields=['requested_at'], name='audit_reque_request_090cf5_idx')],
            },
        ),
    ]
