# Generated by Django 6.0.3 on 2026-03-19 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditrequest',
            index=models.Index(fields=['status'], name='audit_reque_status_a9cebe_idx'),
        ),
        migrations.AddIndex(
            model_name='auditrequest',
            index=models.Index(fields=['table_name', 'record_id'], name='audit_reque_table_n_b278b8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditrequest',
            index=models.Index(fields=['requested_by'], name='audit_reque_request_0625b0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditrequest',
            index=models.Index(fields=['requested_at'], name='audit_reque_request_090cf5_idx'),
        ),
    ]
