# Generated by Django 6.0.3 on 2026-05-18 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditrequest',
            index=models.Index(fields=['status', 'school'], name='audit_status_school_idx'),
        ),
    ]
