# Generated by Django 6.0.3 on 2026-06-15 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditrequest_audit_status_school_idx'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditrequest',
            name='audit_status_school_idx',
        ),
        migrations.AddIndex(
            model_name='auditrequest',
            index=models.Index(fields=['school', 'status', 'requested_at'], name='audit_school_status_reqat_idx'),
        ),
        migrations.AddIndex(
            model_name='auditrequest',
            index=models.Index(fields=['school', 'status', 'reviewed_at'], name='audit_school_status_revat_idx'),
        ),
    ]
