# Generated by Django 6.0.3 on 2026-03-19 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditrequest_audit_reque_status_a9cebe_idx_and_more'),
        ('schools', '0002_campus_school_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrequest',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_requests', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='auditrequest',
            name='table_name',
            field=models.CharField(choices=[('exams_conducted', 'Exams Conducted'), ('school_activities', 'School Activities'), ('student_activities', 'Student Activities'), ('faculty_fdp_workshop_gl', 'Faculty FDP / Workshop / GL'), ('faculty_publications', 'Faculty Publications'), ('patents', 'Patents'), ('certifications', 'Certifications'), ('placement_activities', 'Placement Activities'), ('courses', 'Courses'), ('academic_years', 'Academic Years'), ('semesters', 'Semesters'), ('subjects', 'Subjects'), ('class_groups', 'Class Groups'), ('exam_groups', 'Exam Groups'), ('clubs', 'Clubs')], max_length=100),
        ),
    ]
