# Generated by Django 6.0.3 on 2026-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_mis_coordinator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_service_admin',
            field=models.BooleanField(default=False),
        ),
    ]
