# Generated by Django 6.0.3 on 2026-05-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_service_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('master', 'Master'), ('super_admin', 'Super Admin'), ('admin', 'Admin'), ('user', 'User'), ('delete_auth', 'Delete Auth'), ('mis_coordinator', 'MIS Coordinator'), ('service_admin', 'Service Admin')], max_length=20),
        ),
    ]
