# Generated by Django 6.0.3 on 2026-05-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('master', 'Master'), ('super_admin', 'Super Admin'), ('admin', 'Admin'), ('user', 'User'), ('delete_auth', 'Delete Auth'), ('mis_coordinator', 'MIS Coordinator'), ('mis_accumulator', 'MIS Accumulator'), ('service_admin', 'Service Admin')], max_length=20),
        ),
    ]
