# Generated by Django 6.0.3 on 2026-05-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_chronicle_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('master', 'Master'), ('super_admin', 'Super Admin'), ('admin', 'Admin'), ('user', 'User'), ('delete_auth', 'Delete Auth'), ('mis_coordinator', 'MIS Coordinator'), ('mis_accumulator', 'MIS Accumulator'), ('chronicle_master', 'Chronicle Master'), ('service_admin', 'Service Admin')], max_length=20),
        ),
    ]
