# Generated by Django 6.0.3 on 2026-03-16 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('title_of_course', models.CharField(max_length=500)),
                ('details', models.TextField(blank=True, null=True)),
                ('agency', models.CharField(max_length=255)),
                ('credly_or_proof_link', models.CharField(blank=True, max_length=500, null=True)),
                ('person_type', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student')], default='faculty', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='certifications_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='certifications', to='schools.school')),
            ],
            options={
                'db_table': 'certifications',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExamsConducted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=500)),
                ('examination', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('expected_graduation_year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exams_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to='schools.school')),
            ],
            options={
                'db_table': 'exams_conducted',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FacultyFDPWorkshopGL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('type', models.CharField(choices=[('FDP', 'FDP'), ('Workshop', 'Workshop'), ('Guest_Lecture', 'Guest Lecture')], max_length=20)),
                ('organizing_body', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fdp_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fdp_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fdp_activities', to='schools.school')),
            ],
            options={
                'db_table': 'faculty_fdp_workshop_gl',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='FacultyPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_type', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student')], default='faculty', max_length=10)),
                ('title_of_paper', models.CharField(max_length=1000)),
                ('journal_or_conference_name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=500, null=True)),
                ('publication', models.CharField(blank=True, max_length=255, null=True)),
                ('doi_or_link', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='publications_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='publications', to='schools.school')),
            ],
            options={
                'db_table': 'faculty_publications',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_type', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student')], default='faculty', max_length=10)),
                ('title_of_patent', models.CharField(max_length=1000)),
                ('details', models.TextField(blank=True, null=True)),
                ('date_of_publication', models.DateField()),
                ('journal_number', models.CharField(max_length=100)),
                ('patent_status', models.CharField(choices=[('filed', 'Filed'), ('published', 'Published'), ('granted', 'Granted')], default='filed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='patents_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patents_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='patents', to='schools.school')),
            ],
            options={
                'db_table': 'patents',
                'ordering': ['-date_of_publication'],
            },
        ),
        migrations.CreateModel(
            name='PlacementActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('details', models.TextField()),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='placements_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='placements', to='schools.school')),
            ],
            options={
                'db_table': 'placement_activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('details', models.TextField()),
                ('is_school_wide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='school_activities_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_activities_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='school_activities', to='schools.school')),
            ],
            options={
                'db_table': 'school_activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('details', models.TextField()),
                ('conducted_by', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('club', 'Club'), ('committee', 'Committee'), ('other', 'Other')], default='club', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_activities_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_activities_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_activities', to='schools.school')),
            ],
            options={
                'db_table': 'student_activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentActivityCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborating_club_or_committee', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='records.studentactivity')),
                ('collaborating_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_activity_collaborations', to='schools.school')),
            ],
            options={
                'db_table': 'student_activity_collaborations',
            },
        ),
        migrations.CreateModel(
            name='SchoolActivityCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='records.schoolactivity')),
                ('collaborating_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_collaborations', to='schools.school')),
            ],
            options={
                'db_table': 'school_activity_collaborations',
                'unique_together': {('activity', 'collaborating_school')},
            },
        ),
    ]
