# Generated by Django 6.0.3 on 2026-04-25 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='Weekly or Monthly automated backups', max_length=10)),
                ('schedule_day', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for weekly backups', null=True)),
                ('backup_scope', models.CharField(choices=[('full', 'From Beginning (Full Backup)'), ('date_range', 'Date Range')], default='full', help_text='Scope for manual backups', max_length=15)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Configuration',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('club', 'Club'), ('committee', 'Committee'), ('placecom', 'Placement Committee')], default='club', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clubs_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='schools.school')),
            ],
            options={
                'db_table': 'clubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacultyFDPWorkshopGL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('type', models.CharField(choices=[('FDP', 'FDP'), ('Workshop', 'Workshop'), ('Guest_Lecture', 'Guest Lecture')], max_length=20)),
                ('organizing_body', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fdp_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fdp_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fdp_activities', to='schools.school')),
            ],
            options={
                'db_table': 'faculty_fdp_workshop_gl',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='FacultyPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_type', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student')], default='faculty', max_length=10)),
                ('title_of_paper', models.CharField(max_length=1000)),
                ('journal_or_conference_name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=500, null=True)),
                ('publication', models.CharField(blank=True, max_length=255, null=True)),
                ('doi_or_link', models.CharField(default='', help_text='DOI or direct link to publication', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_own_work', models.BooleanField(default=True, help_text='Faculty marking this as their own publication')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='publications_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='publications', to='schools.school')),
            ],
            options={
                'db_table': 'faculty_publications',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_type', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student')], default='faculty', max_length=10)),
                ('title_of_patent', models.CharField(max_length=1000)),
                ('details', models.TextField(blank=True, null=True)),
                ('date_of_publication', models.DateField()),
                ('journal_number', models.CharField(max_length=100)),
                ('patent_status', models.CharField(choices=[('filed', 'Filed'), ('published', 'Published'), ('granted', 'Granted')], default='filed', max_length=20)),
                ('doi_or_link', models.CharField(default='', help_text='DOI or direct link to patent', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_own_work', models.BooleanField(default=True, help_text='Faculty marking this as their own patent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='patents_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patents_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='patents', to='schools.school')),
            ],
            options={
                'db_table': 'patents',
                'ordering': ['-date_of_publication'],
            },
        ),
        migrations.CreateModel(
            name='PatentApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('applicant_type', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student')], default='faculty', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='records.patent')),
            ],
            options={
                'db_table': 'patent_applicants',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlacementActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('details', models.TextField()),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('placecom_name', models.CharField(blank=True, help_text='Name of the placement committee', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='placements_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='placements', to='schools.school')),
            ],
            options={
                'db_table': 'placement_activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author_type', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student')], default='faculty', max_length=10)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary/corresponding author')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Author order in publication')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='records.facultypublication')),
            ],
            options={
                'db_table': 'publication_authors',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('details', models.TextField()),
                ('is_school_wide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='school_activities_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_activities_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='school_activities', to='schools.school')),
            ],
            options={
                'db_table': 'school_activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolActivityCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='records.schoolactivity')),
                ('collaborating_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_collaborations', to='schools.school')),
            ],
            options={
                'db_table': 'school_activity_collaborations',
            },
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('details', models.TextField()),
                ('club_name', models.CharField(blank=True, help_text='Auto-filled from club, or manual entry', max_length=255, null=True)),
                ('conducted_by', models.CharField(blank=True, help_text='Free text if club not in list', max_length=255, null=True)),
                ('activity_type', models.CharField(choices=[('club', 'Club'), ('committee', 'Committee'), ('other', 'Other')], default='club', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('club', models.ForeignKey(blank=True, help_text='Select from registered clubs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_activities', to='records.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_activities_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_activities_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_activities', to='schools.school')),
            ],
            options={
                'db_table': 'student_activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentActivityCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborating_club_or_committee', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='records.studentactivity')),
                ('collaborating_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_activity_collaborations', to='schools.school')),
            ],
            options={
                'db_table': 'student_activity_collaborations',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('title_of_course', models.CharField(max_length=500)),
                ('details', models.TextField(blank=True, null=True)),
                ('agency', models.CharField(max_length=255)),
                ('credly_or_proof_link', models.CharField(default='', help_text='Credly badge or certificate proof link', max_length=500)),
                ('person_type', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student')], default='faculty', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='certifications_created', to=settings.AUTH_USER_MODEL)),
                ('pending_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_pending', to='audit.auditrequest')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='certifications', to='schools.school')),
            ],
            options={
                'db_table': 'certifications',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['school', 'is_deleted'], name='certificati_school__380976_idx'), models.Index(fields=['date'], name='certificati_date_ae4e7d_idx'), models.Index(fields=['created_by'], name='certificati_created_05fe9c_idx'), models.Index(fields=['agency'], name='certificati_agency_229402_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['school', 'type', 'is_active'], name='clubs_school__896e93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='club',
            unique_together={('name', 'school', 'type')},
        ),
        migrations.AddIndex(
            model_name='facultyfdpworkshopgl',
            index=models.Index(fields=['school', 'is_deleted'], name='faculty_fdp_school__74c5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyfdpworkshopgl',
            index=models.Index(fields=['date_start'], name='faculty_fdp_date_st_6ff949_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyfdpworkshopgl',
            index=models.Index(fields=['type'], name='faculty_fdp_type_b71338_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyfdpworkshopgl',
            index=models.Index(fields=['created_by'], name='faculty_fdp_created_f365af_idx'),
        ),
        migrations.AddIndex(
            model_name='facultypublication',
            index=models.Index(fields=['school', 'is_deleted'], name='faculty_pub_school__4cf5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='facultypublication',
            index=models.Index(fields=['date'], name='faculty_pub_date_7ec318_idx'),
        ),
        migrations.AddIndex(
            model_name='facultypublication',
            index=models.Index(fields=['created_by'], name='faculty_pub_created_93d655_idx'),
        ),
        migrations.AddIndex(
            model_name='facultypublication',
            index=models.Index(fields=['author_type'], name='faculty_pub_author__54a8f9_idx'),
        ),
        migrations.AddIndex(
            model_name='patent',
            index=models.Index(fields=['school', 'is_deleted'], name='patents_school__2b7262_idx'),
        ),
        migrations.AddIndex(
            model_name='patent',
            index=models.Index(fields=['date_of_publication'], name='patents_date_of_a05e89_idx'),
        ),
        migrations.AddIndex(
            model_name='patent',
            index=models.Index(fields=['created_by'], name='patents_created_c043ad_idx'),
        ),
        migrations.AddIndex(
            model_name='patent',
            index=models.Index(fields=['patent_status'], name='patents_patent__30da0a_idx'),
        ),
        migrations.AddIndex(
            model_name='placementactivity',
            index=models.Index(fields=['school', 'is_deleted'], name='placement_a_school__bdb0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='placementactivity',
            index=models.Index(fields=['date'], name='placement_a_date_35ca8b_idx'),
        ),
        migrations.AddIndex(
            model_name='placementactivity',
            index=models.Index(fields=['created_by'], name='placement_a_created_e7fd2e_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolactivity',
            index=models.Index(fields=['school', 'is_deleted'], name='school_acti_school__809810_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolactivity',
            index=models.Index(fields=['date'], name='school_acti_date_b93cda_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolactivity',
            index=models.Index(fields=['created_by'], name='school_acti_created_02e2ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolactivitycollaboration',
            unique_together={('activity', 'collaborating_school')},
        ),
        migrations.AddIndex(
            model_name='studentactivity',
            index=models.Index(fields=['school', 'is_deleted'], name='student_act_school__d310e1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentactivity',
            index=models.Index(fields=['date'], name='student_act_date_e80a80_idx'),
        ),
        migrations.AddIndex(
            model_name='studentactivity',
            index=models.Index(fields=['created_by'], name='student_act_created_0b2e5c_idx'),
        ),
    ]
