# Generated by Django 6.0.3 on 2026-03-18 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsconducted',
            name='course',
        ),
        migrations.RemoveField(
            model_name='examsconducted',
            name='examination',
        ),
        migrations.RemoveField(
            model_name='examsconducted',
            name='expected_graduation_year',
        ),
        migrations.AddField(
            model_name='examsconducted',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to='academics.classgroup'),
        ),
        migrations.AddField(
            model_name='examsconducted',
            name='exam_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to='academics.examgroup'),
        ),
        migrations.AddField(
            model_name='examsconducted',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='exams_conducted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examsconducted',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='placementactivity',
            name='placecom',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'placecom'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_activities', to='academics.club'),
        ),
        migrations.AddField(
            model_name='studentactivity',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_activities', to='academics.club'),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='conducted_by',
            field=models.CharField(blank=True, help_text='Free text if club not in list', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=50)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_absent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='marks_entered', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='records.examsconducted')),
            ],
            options={
                'db_table': 'student_marks',
                'ordering': ['roll_number'],
                'unique_together': {('exam', 'roll_number')},
            },
        ),
    ]
