# Generated by Django 6.0.3 on 2026-05-18 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditrequest_audit_status_school_idx'),
        ('records', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivity',
            name='club_name',
            field=models.CharField(blank=True, help_text='Denormalised snapshot of club name (fallback for free-text entries). Changes to Club.name are intentionally NOT cascaded to this field.', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='facultypublication',
            index=models.Index(fields=['school', 'is_deleted', 'date'], name='pub_school_deleted_date_idx'),
        ),
        migrations.AddIndex(
            model_name='facultypublication',
            index=models.Index(fields=['created_by', 'is_deleted'], name='pub_created_by_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolactivity',
            index=models.Index(fields=['school', 'is_deleted', 'date'], name='sact_school_deleted_date_idx'),
        ),
        migrations.AddIndex(
            model_name='studentactivity',
            index=models.Index(fields=['school', 'is_deleted', 'date'], name='stact_school_deleted_date_idx'),
        ),
    ]
