# Generated by Django 6.0.3 on 2026-03-19 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_examsconducted_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultypublication',
            name='is_own_work',
            field=models.BooleanField(default=True, help_text='Faculty marking this as their own publication'),
        ),
        migrations.AddField(
            model_name='patent',
            name='is_own_work',
            field=models.BooleanField(default=True, help_text='Faculty marking this as their own patent'),
        ),
        migrations.CreateModel(
            name='PatentApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('applicant_type', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student')], default='faculty', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='records.patent')),
            ],
            options={
                'db_table': 'patent_applicants',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author_type', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student')], default='faculty', max_length=10)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary/corresponding author')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Author order in publication')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='records.facultypublication')),
            ],
            options={
                'db_table': 'publication_authors',
                'ordering': ['order'],
            },
        ),
    ]
