# Generated by Django 6.0.3 on 2026-05-18 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditrequest_audit_status_school_idx'),
        ('records', '0002_alter_studentactivity_club_name_and_more'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['school', 'is_deleted', 'date'], name='cert_school_deleted_date_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyfdpworkshopgl',
            index=models.Index(fields=['school', 'is_deleted', 'date_start'], name='fdp_school_deleted_date_idx'),
        ),
        migrations.AddIndex(
            model_name='patent',
            index=models.Index(fields=['school', 'is_deleted', 'date_of_publication'], name='patent_school_deleted_date_idx'),
        ),
        migrations.AddIndex(
            model_name='placementactivity',
            index=models.Index(fields=['school', 'is_deleted', 'date'], name='plcmt_school_del_date_idx'),
        ),
    ]
