# Generated by Django 6.0.3 on 2026-05-29 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_composite_indexes_fdp_patent_cert_placement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patentapplicant',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked registered user (faculty/admin/super_admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_applied_patents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicationauthor',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked registered user (faculty/admin/super_admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_authored_publications', to=settings.AUTH_USER_MODEL),
        ),
    ]
