# Generated by Django 6.0.3 on 2026-03-19 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_facultyteachingassignment_faculty_tea_faculty_41772c_idx_and_more'),
        ('audit', '0002_auditrequest_audit_reque_status_a9cebe_idx_and_more'),
        ('records', '0003_facultypublication_is_own_work_patent_is_own_work_and_more'),
        ('schools', '0002_campus_school_campus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['school', 'is_deleted'], name='certificati_school__380976_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['date'], name='certificati_date_ae4e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['created_by'], name='certificati_created_05fe9c_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['agency'], name='certificati_agency_229402_idx'),
        ),
        migrations.AddIndex(
            model_name='examsconducted',
            index=models.Index(fields=['school', 'is_deleted'], name='exams_condu_school__4cf85a_idx'),
        ),
        migrations.AddIndex(
            model_name='examsconducted',
            index=models.Index(fields=['created_by'], name='exams_condu_created_949119_idx'),
        ),
        migrations.AddIndex(
            model_name='examsconducted',
            index=models.Index(fields=['date'], name='exams_condu_date_7b3e34_idx'),
        ),
        migrations.AddIndex(
            model_name='examsconducted',
            index=models.Index(fields=['exam_group'], name='exams_condu_exam_gr_c62dea_idx'),
        ),
        migrations.AddIndex(
            model_name='examsconducted',
            index=models.Index(fields=['class_group'], name='exams_condu_class_g_c988f1_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyfdpworkshopgl',
            index=models.Index(fields=['school', 'is_deleted'], name='faculty_fdp_school__74c5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyfdpworkshopgl',
            index=models.Index(fields=['date_start'], name='faculty_fdp_date_st_6ff949_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyfdpworkshopgl',
            index=models.Index(fields=['type'], name='faculty_fdp_type_b71338_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyfdpworkshopgl',
            index=models.Index(fields=['created_by'], name='faculty_fdp_created_f365af_idx'),
        ),
        migrations.AddIndex(
            model_name='facultypublication',
            index=models.Index(fields=['school', 'is_deleted'], name='faculty_pub_school__4cf5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='facultypublication',
            index=models.Index(fields=['date'], name='faculty_pub_date_7ec318_idx'),
        ),
        migrations.AddIndex(
            model_name='facultypublication',
            index=models.Index(fields=['created_by'], name='faculty_pub_created_93d655_idx'),
        ),
        migrations.AddIndex(
            model_name='facultypublication',
            index=models.Index(fields=['author_type'], name='faculty_pub_author__54a8f9_idx'),
        ),
        migrations.AddIndex(
            model_name='patent',
            index=models.Index(fields=['school', 'is_deleted'], name='patents_school__2b7262_idx'),
        ),
        migrations.AddIndex(
            model_name='patent',
            index=models.Index(fields=['date_of_publication'], name='patents_date_of_a05e89_idx'),
        ),
        migrations.AddIndex(
            model_name='patent',
            index=models.Index(fields=['created_by'], name='patents_created_c043ad_idx'),
        ),
        migrations.AddIndex(
            model_name='patent',
            index=models.Index(fields=['patent_status'], name='patents_patent__30da0a_idx'),
        ),
        migrations.AddIndex(
            model_name='placementactivity',
            index=models.Index(fields=['school', 'is_deleted'], name='placement_a_school__bdb0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='placementactivity',
            index=models.Index(fields=['date'], name='placement_a_date_35ca8b_idx'),
        ),
        migrations.AddIndex(
            model_name='placementactivity',
            index=models.Index(fields=['created_by'], name='placement_a_created_e7fd2e_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolactivity',
            index=models.Index(fields=['school', 'is_deleted'], name='school_acti_school__809810_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolactivity',
            index=models.Index(fields=['date'], name='school_acti_date_b93cda_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolactivity',
            index=models.Index(fields=['created_by'], name='school_acti_created_02e2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='studentactivity',
            index=models.Index(fields=['school', 'is_deleted'], name='student_act_school__d310e1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentactivity',
            index=models.Index(fields=['date'], name='student_act_date_e80a80_idx'),
        ),
        migrations.AddIndex(
            model_name='studentactivity',
            index=models.Index(fields=['created_by'], name='student_act_created_0b2e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmarks',
            index=models.Index(fields=['exam'], name='student_mar_exam_id_f80d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmarks',
            index=models.Index(fields=['roll_number'], name='student_mar_roll_nu_cb65c5_idx'),
        ),
    ]
