# Generated by Django 6.0.3 on 2026-06-15 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_add_user_fk_to_publication_author_patent_applicant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patentapplicant',
            index=models.Index(fields=['patent'], name='patent_appl_patent__7f6328_idx'),
        ),
        migrations.AddIndex(
            model_name='patentapplicant',
            index=models.Index(fields=['user'], name='patapp_user_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationauthor',
            index=models.Index(fields=['publication'], name='publication_publica_07fc35_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationauthor',
            index=models.Index(fields=['user'], name='pubauthor_user_idx'),
        ),
    ]
