# Generated by Django 6.0.3 on 2026-03-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_backupconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupconfiguration',
            name='interval_hours',
        ),
        migrations.RemoveField(
            model_name='backupconfiguration',
            name='retention_days',
        ),
        migrations.AddField(
            model_name='backupconfiguration',
            name='backup_scope',
            field=models.CharField(choices=[('full', 'From Beginning (Full Backup)'), ('date_range', 'Date Range')], default='full', help_text='Scope for manual backups', max_length=15),
        ),
        migrations.AddField(
            model_name='backupconfiguration',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupconfiguration',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupconfiguration',
            name='schedule_day',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for weekly backups', null=True),
        ),
        migrations.AddField(
            model_name='backupconfiguration',
            name='schedule_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='Weekly or Monthly automated backups', max_length=10),
        ),
    ]
