# Generated by Django 6.0.3 on 2026-03-18 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='schools.school')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['name'],
                'unique_together': {('school', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.PositiveSmallIntegerField(help_text='e.g. 1 for first year, 2 for second year')),
                ('graduation_year', models.PositiveSmallIntegerField(help_text='e.g. 2027')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='academic_years_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='academic_years', to='schools.school')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='academic_years', to='academics.course')),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['course', 'year_number'],
                'unique_together': {('course', 'year_number', 'graduation_year')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveSmallIntegerField(help_text='e.g. 1 through 8')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='semesters', to='academics.academicyear')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='semesters_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'semesters',
                'ordering': ['academic_year', 'semester_number'],
                'unique_together': {('academic_year', 'semester_number')},
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('club', 'Club'), ('committee', 'Committee'), ('placecom', 'Placement Committee')], default='club', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clubs_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clubs', to='schools.school')),
            ],
            options={
                'db_table': 'clubs',
                'ordering': ['type', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. CSDS-A, CSE-B, CE-A', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='class_groups_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='class_groups', to='schools.school')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='class_groups', to='academics.course')),
            ],
            options={
                'db_table': 'class_groups',
                'ordering': ['course', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Mid Term 1, End Semester', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exam_groups_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exam_groups', to='schools.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exam_groups', to='academics.semester')),
            ],
            options={
                'db_table': 'exam_groups',
                'ordering': ['semester', 'name'],
                'unique_together': {('semester', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subjects_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subjects', to='schools.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subjects', to='academics.semester')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['semester', 'name'],
                'unique_together': {('semester', 'code')},
            },
        ),
    ]
