# Generated by Django 6.0.3 on 2026-03-18 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examgroup',
            name='class_groups',
            field=models.ManyToManyField(blank=True, help_text='Class groups included in this exam group', related_name='exam_groups', to='academics.classgroup'),
        ),
        migrations.AlterField(
            model_name='examgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='FacultyTeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes on approval/rejection', null=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teaching_assignments', to='academics.classgroup')),
                ('faculty', models.ForeignKey(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teaching_assignments', to='schools.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teaching_assignments', to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teaching_assignments', to='academics.subject')),
            ],
            options={
                'db_table': 'faculty_teaching_assignments',
                'ordering': ['-requested_at'],
                'unique_together': {('faculty', 'subject', 'class_group')},
            },
        ),
    ]
