# Generated by Django 6.0.3 on 2026-03-19 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_examgroup_class_groups_alter_examgroup_name_and_more'),
        ('schools', '0002_campus_school_campus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='facultyteachingassignment',
            index=models.Index(fields=['faculty', 'status'], name='faculty_tea_faculty_41772c_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyteachingassignment',
            index=models.Index(fields=['school', 'status'], name='faculty_tea_school__be43d1_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyteachingassignment',
            index=models.Index(fields=['status'], name='faculty_tea_status_21cf3f_idx'),
        ),
    ]
