# Generated by Django 6.0.3 on 2026-03-19 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_facultyteachingassignment_faculty_tea_faculty_41772c_idx_and_more'),
        ('audit', '0002_auditrequest_audit_reque_status_a9cebe_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='pending_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_years_pending', to='audit.auditrequest'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='pending_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups_pending', to='audit.auditrequest'),
        ),
        migrations.AddField(
            model_name='club',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='pending_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_pending', to='audit.auditrequest'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='pending_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_pending', to='audit.auditrequest'),
        ),
        migrations.AddField(
            model_name='examgroup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examgroup',
            name='pending_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_groups_pending', to='audit.auditrequest'),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='pending_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semesters_pending', to='audit.auditrequest'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='pending_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_pending', to='audit.auditrequest'),
        ),
    ]
