# Generated by Django 6.0.3 on 2026-05-30 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(choices=[('frontend_js', 'Frontend JS Error'), ('api_error', 'API / Network Error'), ('manual', 'Manually Reported')], default='frontend_js', max_length=20)),
                ('error_type', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('component_stack', models.TextField(blank=True, null=True)),
                ('url_path', models.CharField(blank=True, max_length=1000)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('api_endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('affected_users_count', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('wontfix', "Won't Fix")], default='open', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_error_tickets',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='ErrorOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('url_path', models.CharField(blank=True, max_length=1000)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_occurrences', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='service.errorticket')),
            ],
            options={
                'db_table': 'service_error_occurrences',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url_path', models.CharField(blank=True, max_length=1000)),
                ('severity', models.CharField(choices=[('low', 'Low — Minor inconvenience'), ('medium', 'Medium — Feature is broken'), ('high', 'High — Cannot complete my work'), ('critical', 'Critical — Data loss / security issue')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('linked', 'Linked to Ticket'), ('resolved', 'Resolved'), ('wontfix', "Won't Fix")], default='open', max_length=15)),
                ('screenshot', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
                ('linked_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to='service.errorticket')),
            ],
            options={
                'db_table': 'service_bug_reports',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='errorticket',
            index=models.Index(fields=['status'], name='service_err_status_c58e22_idx'),
        ),
        migrations.AddIndex(
            model_name='errorticket',
            index=models.Index(fields=['source'], name='service_err_source_0ac382_idx'),
        ),
        migrations.AddIndex(
            model_name='errorticket',
            index=models.Index(fields=['first_seen'], name='service_err_first_s_178f23_idx'),
        ),
        migrations.AddIndex(
            model_name='errorticket',
            index=models.Index(fields=['occurrence_count'], name='service_err_occurre_4b9a50_idx'),
        ),
        migrations.AddIndex(
            model_name='erroroccurrence',
            index=models.Index(fields=['ticket', 'occurred_at'], name='service_err_ticket__6ccbc5_idx'),
        ),
        migrations.AddIndex(
            model_name='erroroccurrence',
            index=models.Index(fields=['user'], name='service_err_user_id_3037ea_idx'),
        ),
        migrations.AddIndex(
            model_name='bugreport',
            index=models.Index(fields=['status'], name='service_bug_status_76544d_idx'),
        ),
        migrations.AddIndex(
            model_name='bugreport',
            index=models.Index(fields=['severity'], name='service_bug_severit_212f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='bugreport',
            index=models.Index(fields=['submitted_at'], name='service_bug_submitt_f3266a_idx'),
        ),
    ]
