# Generated by Django 6.0.3 on 2026-05-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('planning', 'Planning'), ('fixing', 'Fixing'), ('testing', 'Testing'), ('closed', 'Closed')], default='open', max_length=15),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('planning', 'Planning'), ('fixing', 'Fixing'), ('testing', 'Testing'), ('closed', 'Closed')], default='open', max_length=15),
        ),
    ]
