# Generated by Django 6.0.3 on 2026-06-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_bugreport_status_alter_errorticket_status'),
    ]

    operations = [
    ]
