import { useState, useEffect, useCallback } from 'react'
import PageHeader from '../../components/ui/PageHeader'
import Button     from '../../components/ui/Button'
import Badge      from '../../components/ui/Badge'
import Table      from '../../components/ui/Table'
import api        from '../../api/axios'

export default function ExportHistory() {
  const [exports,    setExports]    = useState([])
  const [loading,    setLoading]    = useState(true)
  const [triggering, setTriggering] = useState(false)
  const [message,    setMessage]    = useState(null)
  const [currentPage, setCurrentPage] = useState(1)
  const [totalPages,  setTotalPages]  = useState(1)

  const fetchExports = useCallback(() => {
    setLoading(true)
    api.get('/export/history/', { params: { page: currentPage, page_size: 25 } })
      .then(res => {
          setExports(res.data?.results ?? res.data)
          setTotalPages(res.data?.total_pages ?? 1)
      })
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [currentPage])

  useEffect(() => { fetchExports() }, [fetchExports])

  const showMessage = (text, type = 'success') => {
    setMessage({ text, type })
    setTimeout(() => setMessage(null), 4000)
  }

  const handleTriggerNightly = async () => {
    setTriggering(true)
    try {
      await api.post('/export/nightly/trigger/')
      showMessage('Nightly export started. Refresh in a few seconds.')
      setTimeout(fetchExports, 5000)
    } catch {
      showMessage('Failed to trigger export', 'error')
    } finally {
      setTriggering(false)
    }
  }

  const handleDownload = async (exp) => {
    try {
      const res = await api.get(
        `/export/download/${exp.id}/`,
        { responseType: 'blob' }
      )
      const url = window.URL.createObjectURL(new Blob([res.data]))
      const a   = document.createElement('a')
      a.href    = url
      a.download = exp.filename
      a.click()
      window.URL.revokeObjectURL(url)
    } catch {
      showMessage('Download failed — file may no longer exist', 'error')
    }
  }

  const columns = [
    {
      key: 'campus', label: 'Campus', render: exp => (
        <>
          <p className="font-medium text-gray-800">{exp.campus}</p>
          <p className="text-xs text-gray-400">{exp.campus_code}</p>
        </>
      )
    },
    {
      key: 'export_type', label: 'Type', render: exp => (
        <Badge label={exp.export_type} color={exp.export_type === 'nightly' ? 'blue' : 'purple'} />
      )
    },
    {
      key: 'record_count', label: 'Records', render: exp => <span className="text-gray-600">{exp.record_count.toLocaleString()}</span>
    },
    {
      key: 'file_size_kb', label: 'Size', render: exp => <span className="text-gray-500">{exp.file_size_kb} KB</span>
    },
    {
      key: 'generated_by', label: 'Generated By', render: exp => <span className="text-gray-600">{exp.generated_by}</span>
    },
    {
      key: 'generated_at', label: 'Date', render: exp => <span className="text-gray-500 text-xs">{exp.generated_at?.slice(0, 16).replace('T', ' ')}</span>
    },
    {
      key: 'actions', label: '', sortable: false, render: exp => (
        <Button size="sm" variant="secondary" onClick={() => handleDownload(exp)}>
          ⬇ Download
        </Button>
      )
    }
  ]

  return (
    <div>
      <PageHeader
        title="Export History"
        subtitle="All nightly and manual exports across all campuses"
        action={
          <div className="flex gap-2">
            <Button
              variant="secondary"
              onClick={fetchExports}
            >
              ↻ Refresh
            </Button>
            <Button
              onClick={handleTriggerNightly}
              loading={triggering}
            >
              ▶ Run Nightly Export Now
            </Button>
          </div>
        }
      />

      {message && (
        <div className={`mb-4 p-3 rounded-xl text-sm
          ${message.type === 'success'
            ? 'bg-green-50 border border-green-200 text-green-700'
            : 'bg-red-50 border border-red-200 text-red-600'
          }`}>
          {message.text}
        </div>
      )}

      <Table
        columns={columns}
        data={exports}
        loading={loading}
        serverPagination
        totalPages={totalPages}
        currentPage={currentPage}
        onPageChange={setCurrentPage}
      />
    </div>
  )
}
