import { useState, useEffect, useCallback } from 'react'
import PageHeader from '../../components/ui/PageHeader'
import Button     from '../../components/ui/Button'
import Badge      from '../../components/ui/Badge'
import api        from '../../api/axios'

export default function ExportHistory() {
  const [exports,    setExports]    = useState([])
  const [loading,    setLoading]    = useState(true)
  const [triggering, setTriggering] = useState(false)
  const [message,    setMessage]    = useState(null)

  const fetchExports = useCallback(() => {
    setLoading(true)
    api.get('/export/history/')
      .then(res => setExports(res.data?.results ?? res.data))
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [])

  useEffect(() => { fetchExports() }, [fetchExports])

  const showMessage = (text, type = 'success') => {
    setMessage({ text, type })
    setTimeout(() => setMessage(null), 4000)
  }

  const handleTriggerNightly = async () => {
    setTriggering(true)
    try {
      await api.post('/export/nightly/trigger/')
      showMessage('Nightly export started. Refresh in a few seconds.')
      setTimeout(fetchExports, 5000)
    } catch {
      showMessage('Failed to trigger export', 'error')
    } finally {
      setTriggering(false)
    }
  }

  const handleDownload = async (exp) => {
    try {
      const res = await api.get(
        `/export/download/${exp.id}/`,
        { responseType: 'blob' }
      )
      const url = window.URL.createObjectURL(new Blob([res.data]))
      const a   = document.createElement('a')
      a.href    = url
      a.download = exp.filename
      a.click()
      window.URL.revokeObjectURL(url)
    } catch {
      showMessage('Download failed — file may no longer exist', 'error')
    }
  }

  return (
    <div>
      <PageHeader
        title="Export History"
        subtitle="All nightly and manual exports across all campuses"
        action={
          <div className="flex gap-2">
            <Button
              variant="secondary"
              onClick={fetchExports}
            >
              ↻ Refresh
            </Button>
            <Button
              onClick={handleTriggerNightly}
              loading={triggering}
            >
              ▶ Run Nightly Export Now
            </Button>
          </div>
        }
      />

      {message && (
        <div className={`mb-4 p-3 rounded-xl text-sm
          ${message.type === 'success'
            ? 'bg-green-50 border border-green-200 text-green-700'
            : 'bg-red-50 border border-red-200 text-red-600'
          }`}>
          {message.text}
        </div>
      )}

      {loading ? (
        <div className="flex justify-center py-16">
          <div className="animate-spin rounded-full h-8 w-8
                          border-b-2 border-primary-600" />
        </div>
      ) : exports.length === 0 ? (
        <div className="text-center py-16 text-gray-400 text-sm">
          No exports generated yet.
          Click "Run Nightly Export Now" to generate the first one.
        </div>
      ) : (
        <div className="bg-white rounded-xl border border-gray-100 overflow-hidden">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 border-b border-gray-100">
              <tr>
                {['Campus', 'Type', 'Records',
                  'Size', 'Generated By', 'Date', ''].map(h => (
                  <th key={h}
                    className="px-4 py-3 text-left text-xs
                               font-medium text-gray-500 uppercase">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {exports.map(exp => (
                <tr key={exp.id} className="hover:bg-gray-50">
                  <td className="px-4 py-3">
                    <p className="font-medium text-gray-800">
                      {exp.campus}
                    </p>
                    <p className="text-xs text-gray-400">
                      {exp.campus_code}
                    </p>
                  </td>
                  <td className="px-4 py-3">
                    <Badge
                      label={exp.export_type}
                      color={exp.export_type === 'nightly' ? 'blue' : 'purple'}
                    />
                  </td>
                  <td className="px-4 py-3 text-gray-600">
                    {exp.record_count.toLocaleString()}
                  </td>
                  <td className="px-4 py-3 text-gray-500">
                    {exp.file_size_kb} KB
                  </td>
                  <td className="px-4 py-3 text-gray-600">
                    {exp.generated_by}
                  </td>
                  <td className="px-4 py-3 text-gray-500 text-xs">
                    {exp.generated_at?.slice(0, 16).replace('T', ' ')}
                  </td>
                  <td className="px-4 py-3">
                    <Button
                      size="sm"
                      variant="secondary"
                      onClick={() => handleDownload(exp)}
                    >
                      ⬇ Download
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}
